version: '3'
services:
  nzbget:
    image: 'linuxserver/nzbget'
    volumes:
      - /srv/mediabox/nzbget:/config
      - /media/data/public/downloads:/downloads
      - /media/data/public/incomplete:/intermediate
    environment:
      PGID: 1000
      PUID: 1000
      TZ: America/Edmonton
    ports:
      - 6789:6789
  sabnzbd:
    image: 'linuxserver/sabnzbd'
    ports:
      - 8080:8080
      - 9090:9090
    volumes:
      - /srv/mediabox/sabnzbd:/config
      - /media/data/public/downloads:/downloads
      - /media/data/public/incomplete:/incomplete-downloads
      - /srv/certs/fullchain.pem:/config/admin/server.crt
      - /srv/certs/privkey.pem:/config/admin/server.key
    environment:
      PGID: 1000
      PUID: 1000
      TZ: America/Edmonton
  sonarr:
    image: 'linuxserver/sonarr'
    ports:
      - 8989:8989
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /srv/mediabox/sonarr:/config
      - /media/data/public/media/tv:/tv
      - /media/data/public/downloads:/downloads
    environment:
      PGID: 1000
      PUID: 1000
      TZ: America/Edmonton
  plex:
    image: 'linuxserver/plex'
    network_mode: "host"
    volumes:
      - /srv/mediabox/plex:/config
      - /media/data/public/media:/data/media
    environment:
      VERSION: latest 
      PGID: 1000
      PUID: 1000
      TZ: America/Edmonton
  radarr:
    image: 'linuxserver/radarr'
    ports:
      - 7878:7878
    volumes:
      - /srv/mediabox/radarr:/config
      - /media/data/public/downloads:/downloads
      - /media/data/public/media/movies:/movies
      - /etc/localtime:/etc/localtime:ro
    environment:
      PGID: 1000
      PUID: 1000
      TZ: America/Edmonton
  rutorrent:
    image: 'linuxserver/rutorrent'
    ports:
      - 2323:80
      - 5000:2324
      - 51413:51413
      - 6881:6881/udp
    volumes:
      - /srv/mediabox/rutorrent:/config
      - /media/data/public/downloads:/downloads
    environment:
      PGID: 1000
      PUID: 1000
      TZ: America/Edmonton
  mylar:
    image: 'linuxserver/mylar'
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /srv/mediabox/mylar:/config
      - /media/data/public/media/comics:/comics
      - /media/data/public/downloads:/downloads
    ports:
      - 8090:8090
    restart: unless-stopped
  portainer:
    image: portainer/portainer
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - /srv/mediabox/portainer:/datra
      - /var/run/docker.sock:/var/run/docker.sock
  organizr:
    image: lsiocommunity/organizr
    ports:
      - 80:80
    volumes:
      - /srv/mediabox/organizr:/config
    environment:
      PGID: 1000
      PUID: 1000
      TZ: America/Edmonton