version: '3'
services:
  hub:
    build: ../hub
    ports:
      - 80:80
  sabnzbd:
    image: 'linuxserver/sabnzbd'
    ports:
      - 8080:8080
      - 9090:9090
    volumes:
      - /data/public/config/sabnzbd:/config
      - /data/public/downloads:/downloads
      - /data/public/incomplete:/incomplete-downloads
    environment:
      PGID: 1000
      PUID: 1000
      TZ: America/Edmonton
  sonarr:
    image: 'linuxserver/sonarr'
    ports:
      - 8989:8989
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /data/public/config/sonarr:/config
      - /data/public/media/tv:/tv
      - /data/public/downloads:/downloads
    environment:
      PGID: 1000
      PUID: 1000
      TZ: America/Edmonton
  plex:
    image: 'linuxserver/plex'
    network_mode: "host"
    volumes:
      - /data/public/config/plex:/config
      - /data/public/media:/data/media
    environment:
      VERSION: latest 
      PGID: 1000
      PUID: 1000
      TZ: America/Edmonton
  couchpotato:
    image: 'linuxserver/couchpotato'
    ports:
      - 5050:5050
    volumes:
      - /data/public/config/couchpotato:/config
      - /data/public/downloads:/downloads
      - /data/public/media/movies:/movies
    environment:
      PGID: 1000
      PUID: 1000
      TZ: America/Edmonton
  rutorrent:
    image: 'linuxserver/rutorrent'
    ports:
      - 2323:80
      - 5000:2324
      - 51413:51413
      - 6881:6881/udp
    volumes:
      - /data/public/config/rutorrent:/config
      - /data/public/downloads:/downloads
    environment:
      PGID: 1000
      PUID: 1000
      TZ: America/Edmonton
